version: "3.9"

services:
  simulator:
    build: .
    command: python simulate_loop.py -interval 1.0
    volumes:
      - ./db:/app/db
      - ./data:/app/data
    restart: always

  dashboard:
    build: .
    command: streamlit run dashboard.py
    ports:
      - "8501:8501"
    volumes:
      - ./db:/app/db
      - ./data:/app/data
    restart: always
